module.exports = [
  {
      "Email Address": "gabriel.s.brasil14@gmail.com",
      "DateCreated": "1/7/2021 5:48:45 AM",
      "CNPJ": "71189278001098",
      "COMPONENT": "contact-form-component",
      "origem": "https://www.serasaexperian.com.br/solucoes-cadastro-positivo",
      "fullname": "Gabriel Silva brasil",
      "SOURCE_APPLICATION": "Site Serasa Experian Frontend",
      "phone": "28999925824",
      "First_Name": "Gabriel",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "Site Institucional",
      "MICRO_SETOR": "REGIOES RJ, MG E ES",
      "MACRO SETOR": "REGIOES",
      "CLASS_MCKINSEY": "GG",
      "cnpj": "71189278"
  },
  {
      "Email Address": "rita.teixeira@moneyp.com.br",
      "DateCreated": "1/7/2021 6:20:00 AM",
      "CNPJ": "11581339000145",
      "COMPONENT": "contact-component",
      "origem": "https://empresas.serasaexperian.com.br/outras-solucoes?idcmp=:c04:m01:googlesearch:CR65:ADG01:AD02:TRLCALL002:d&gclid=CjwKCAiA_9r_BRBZEiwAHZ_v13Hcpkg-BH7CV7C9yWwZd6hhZx2qCNOV2NpsH6Id7aZPlbSRlGtj6xoC8D",
      "fullname": "Rita Teixeira",
      "SOURCE_APPLICATION": "Formulario Leads PME",
      "phone": "11947199648",
      "First_Name": "Rita",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "https://empresas.serasaexperian.com.br/outras-solucoes?idcmp=:c04:m01:googlesearch:CR65:ADG01:AD02:TRLCALL002:d&gclid=CjwKCAiA_9r_BRBZEiwAHZ_v13Hcpkg-BH7CV7C9yWwZd6hhZx2qCNOV2NpsH6Id7aZPlbSRlGtj6xoC8D",
      "MICRO_SETOR": "MPME",
      "MACRO SETOR": "MPME",
      "CLASS_MCKINSEY": "GG",
      "cnpj": "11581339"
  },
  {
      "Email Address": "andre.pinotti@gmail.com",
      "DateCreated": "1/7/2021 8:56:41 AM",
      "CNPJ": "35631200000127",
      "COMPONENT": "contact-form-component",
      "origem": "https://www.serasaexperian.com.br/produtos/gestor-de-credito",
      "fullname": "André Pinotti Azevedo Marques",
      "SOURCE_APPLICATION": "Site Serasa Experian Frontend",
      "phone": "11942221911",
      "First_Name": "André",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "Site Institucional",
      "MICRO_SETOR": "",
      "MACRO SETOR": "",
      "CLASS_MCKINSEY": "",
      "cnpj": "35631200"
  },
  {
      "Email Address": "tpapile@studiovisual.com.br",
      "DateCreated": "1/7/2021 9:30:24 AM",
      "CNPJ": "62173620010495",
      "COMPONENT": "contact-form-component",
      "origem": "http://localhost/",
      "fullname": "Tiago Papile",
      "SOURCE_APPLICATION": "Site Serasa Experian Frontend",
      "phone": "11984948948",
      "First_Name": "Tiago",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "Site Institucional",
      "MICRO_SETOR": "SEM CANAL",
      "MACRO SETOR": "SEM CANAL",
      "CLASS_MCKINSEY": "GG",
      "cnpj": "62173620"
  },
  {
      "Email Address": "bruna@campocapital.com.br",
      "DateCreated": "1/7/2021 11:26:57 AM",
      "CNPJ": "38399700000173",
      "COMPONENT": "contact-form-component",
      "origem": "https://www.serasaexperian.com.br/produtos/powercurve-credito",
      "fullname": "Bruna Aguiar",
      "SOURCE_APPLICATION": "Site Serasa Experian Frontend",
      "phone": "34999440610",
      "First_Name": "Bruna",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "Site Institucional",
      "MICRO_SETOR": "",
      "MACRO SETOR": "",
      "CLASS_MCKINSEY": "",
      "cnpj": "38399700"
  },
  {
      "Email Address": "densilvainternet@gmail.com",
      "DateCreated": "1/7/2021 11:46:31 AM",
      "CNPJ": "33200056000149",
      "COMPONENT": "contact-component",
      "origem": "https://empresas.serasaexperian.com.br/planos/avulso",
      "fullname": "Lojas riachoelo ",
      "SOURCE_APPLICATION": "Formulario Leads PME",
      "phone": "34988377957",
      "First_Name": "Lojas",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "https://empresas.serasaexperian.com.br/planos/avulso",
      "MICRO_SETOR": "MPME",
      "MACRO SETOR": "MPME",
      "CLASS_MCKINSEY": "GG",
      "cnpj": "33200056"
  },
  {
      "Email Address": "jaianne.silva@gruponos.com",
      "DateCreated": "1/7/2021 11:09:58 AM",
      "CNPJ": "26563652000128",
      "COMPONENT": "contact-form-component",
      "origem": "https://www.serasaexperian.com.br/solucoes/consulta-de-credito-e-analytics",
      "fullname": "Jaianne Silva",
      "SOURCE_APPLICATION": "Site Serasa Experian Frontend",
      "phone": "11948518229",
      "First_Name": "Jaianne",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "Site Institucional",
      "MICRO_SETOR": "MULTI_SECTOR",
      "MACRO SETOR": "MULTI-SECTOR",
      "CLASS_MCKINSEY": "GG",
      "cnpj": "26563652"
  },
  {
      "Email Address": "naofsemfi@cariacica.es.gov.br",
      "DateCreated": "1/7/2021 11:05:42 AM",
      "CNPJ": "27150549000119",
      "COMPONENT": "contact-form-component",
      "origem": "https://www.serasaexperian.com.br/",
      "fullname": "PRISCILLA ROSARIO",
      "SOURCE_APPLICATION": "Site Serasa Experian Frontend",
      "phone": "27999214475",
      "First_Name": "PRISCILLA",
      "INTERESSE": "",
      "ATIV_INTERESSE": "",
      "produto": "Site Institucional",
      "MICRO_SETOR": "MULTI_SECTOR",
      "MACRO SETOR": "MULTI-SECTOR",
      "CLASS_MCKINSEY": "GG",
      "cnpj": "27150549"
  }
]